# Site settings
title: "Unblocking Security"
email: andymtruman@gmail.com
description: "An engineers view on DevSecOps and security culture."
baseurl: ""
url: "https://andymtruman.github.io"
title_description: ""
title_image: ""
google_analytics: ""
disqus_account: cartenoire
github_repository: https://github.com/andymtruman
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  andymtruman
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/andymtruman/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
