# Site settings
title: "Unblocking Security"
email: andymtruman@gmail.com
description: "An engineers view on DevSecOps and security culture."
baseurl: ""
url: "https://andymtruman.github.io"
title_description: "An engineers view on DevSecOps and security culture."
title_image: "assets/greyscale.png"
google_analytics: ""
disqus_account: 
github_repository: https://github.com/andymtruman
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  andymtruman
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/andymtruman/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

gems: [jekyll-mermaid]
